title: NimbleUser Apex Style Guide
email: info@nimbleuser.com
description: > # Defines an open source set of coding standards for the Apex programming language.
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
google_analytics: UA-46874006-1